### ISSUE TITLE
Wrong string for OneClassSVM in ALLOWED_CLASSIFIERS

### ISSUE THREAD

**Issue by pwoller** [eloquentarduino/micromlgen#9]
Having a look on the supported model in `platforms.py` I realized that `OneClassSVC` is not a valid `scikit-learn` estimator. It should be `OneClassSVM` as correctly checked in [`is_svm`](https://github.com/eloquentarduino/micromlgen/blob/master/micromlgen/svm.py#L4).

**Comment by eloquentarduino** [comment]
Thank you for the spot, fixed in micromlgen=1.1.24
